{% set name = "asf_search" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd943c9bc5b11a2921f47ec23c77b14814229ec11fefd36ede6ad4437d276df2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - wheel
  run:
    - python >=3.6
    - requests
    - shapely
    - python-dateutil
    - pytz
    - importlib_metadata
    - numpy
    - dateparser

test:
  imports:
    - asf_search
  requires:
    - pip
  commands:
    - pip check
about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
