{% set name = "asf_search" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38bc19e341d943c400c027231e7205008bfdbd3ca2282d36d737d0d03afaa01a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.6
    - requests
    - shapely
    - python-dateutil
    - pytz
    - importlib_metadata
    - numpy
    - dateparser >=1.1.1
    - jinja2
    - remotezip >=0.10.0

test:
  imports:
    - asf_search
  requires:
    - pip
  commands:
    - pip check
about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
