{% set name = "asf_search" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e5ca241fbd77a9e9c6cd07af015dbea44b3181a155b2701fe2e346df6afdb62

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - wheel
  run:
    - python >=3.6
    - numpy
    - python-dateutil
    - pytz
    - requests

test:
  imports:
    - asf_search

about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
